[package]
name = "lottery"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
lottery_addr="0xa07117682b5fffc9046832f396fd4289f0a38b6925abc63148856b35c80604a8"
yield_addr="0x483efcc3335f5eaf91af6b752443b074589dde04df8595937aa161ea9daf7d86"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.yield]
local = "../yield"

[dev-dependencies]
