[package]
name = "yield"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
yield_addr="0x483efcc3335f5eaf91af6b752443b074589dde04df8595937aa161ea9daf7d86"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
